### PR TITLE
Changed unfocusedInactiveForeground for better contrast for titles in tab group that is unfocused

### LINKED ISSUE #12: Not enough contrast on tabs in a tab group that are not in focus
Screenshot 2020-09-29 at 13 41 47

### PR DESCRIPTION
**Pull request by jvik**
Fixes #12

### CODE REVIEW

**Comment by jvik** [comment]
Screenshot 2020-09-29 at 13 58 01

**Comment by sdras** [comment]
Can you please tell me which version you are on and a screenshot of the "before" state you are referring to? I just updated a lot of highlights so trying to make sure this is up to date

**Comment by Amerzel** [comment]
@sdras ,

I'm on 0.3.1 and am seeing the issue @jvik points out. The text color for tabs in a group that is not in focus is black, which makes it hard to see.

Thanks for the awesome theme!

image

James

**Comment by jvik** [comment]
@sdras : I can confirm that this is happening on 0.3.1. Tested on both MacOS and Linux Manjaro.

**Pull request merged**
